"""The write guard.

Model output is data, not authority. Every file the model produces is checked
against an allowlist of paths before it touches the disk, so a pass that
decides it would rather rewrite the Dockerfile simply cannot. The skeleton is
the part we know works; making it unwritable is what keeps that true.
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass
from pathlib import Path

# Only these paths are generated. Everything else in a project is skeleton.
WRITABLE = (
    "app/models.py",
    "app/routes.py",
    "app/seed.py",
    "app/templates/*.html",
    "tests/test_smoke.py",
)

# ...except these, which live under a writable glob but are skeleton.
PROTECTED = ("app/templates/base.html",)

BANNER_PY = "# GENERATED by protogen ({pass_name} pass). Regenerated whole; do not hand-edit.\n"
BANNER_HTML = "{{# GENERATED by protogen ({pass_name} pass). Regenerated whole; do not hand-edit. #}}\n"


class UnsafePath(ValueError):
    """Raised when a pass tries to write somewhere it is not allowed to."""


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str

    def rel(self) -> Path:
        return Path(self.path)


def check_path(path: str) -> Path:
    """Normalise and authorise one model-supplied path."""
    if not path or path.startswith("/") or "\\" in path:
        raise UnsafePath(f"absolute or malformed path: {path!r}")
    rel = Path(path)
    if ".." in rel.parts:
        raise UnsafePath(f"path escapes the project: {path!r}")
    posix = rel.as_posix()
    if posix in PROTECTED:
        raise UnsafePath(f"{posix} is part of the skeleton and is not generated")
    if not any(fnmatch.fnmatch(posix, pattern) for pattern in WRITABLE):
        raise UnsafePath(
            f"{posix} is not a generated path; generated paths are: {', '.join(WRITABLE)}"
        )
    return rel


def banner_for(path: str, pass_name: str) -> str:
    if path.endswith(".html"):
        return BANNER_HTML.format(pass_name=pass_name)
    return BANNER_PY.format(pass_name=pass_name)


def write_all(
    project_dir: Path, files: list[GeneratedFile], pass_name: str
) -> list[Path]:
    """Authorise every path first, then write. All-or-nothing.

    Validating up front matters: a half-applied pass leaves a tree that is
    neither the old one nor the new one, and the repair loop would then be
    debugging a state no pass ever intended to produce.
    """
    checked = [(check_path(f.path), f) for f in files]
    written: list[Path] = []
    for rel, generated in checked:
        dest = project_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        body = generated.content
        banner = banner_for(generated.path, pass_name)
        if "GENERATED by protogen" not in body.split("\n", 3)[0]:
            body = banner + body
        if not body.endswith("\n"):
            body += "\n"
        dest.write_text(body)
        written.append(rel)
    return written
