"""GENERATED by protogen (schema pass). Regenerated whole; do not hand-edit.

The bare skeleton ships this file empty so an unbuilt tree still imports.
"""

from __future__ import annotations

from app.db import Base  # noqa: F401
