"""GENERATED by protogen (seed pass). Regenerated whole; do not hand-edit.

Seeding is idempotent by convention: every generated seed() checks whether
its table already has rows before inserting, because lifespan runs on every
reload and a non-idempotent seed turns hot reload into a duplicate-row factory.
"""

from __future__ import annotations

from sqlalchemy.orm import Session


def seed(db: Session) -> None:
    return None
