from __future__ import annotations

import pytest

from protogen.files import GeneratedFile, UnsafePath, check_path, write_all


@pytest.mark.parametrize(
    "path", ["app/models.py", "app/routes.py", "app/seed.py",
             "app/templates/trips_list.html", "tests/test_smoke.py"]
)
def test_generated_paths_are_allowed(path):
    assert check_path(path)


@pytest.mark.parametrize(
    "path",
    [
        "/etc/passwd",
        "../../etc/passwd",
        "app/../../escape.py",
        "Dockerfile",
        "compose.yml",
        "app/main.py",
        "app/db.py",
        "tests/conftest.py",
        "app/templates/base.html",
    ],
)
def test_skeleton_and_escapes_are_refused(path):
    # Model output is data, not authority. The parts of the tree that are known
    # to work are the parts the model must not be able to touch.
    with pytest.raises(UnsafePath):
        check_path(path)


def test_write_all_is_all_or_nothing(tmp_path):
    files = [
        GeneratedFile("app/models.py", "x = 1\n"),
        GeneratedFile("Dockerfile", "FROM scratch\n"),
    ]
    with pytest.raises(UnsafePath):
        write_all(tmp_path, files, "schema")
    # The legal file must not have landed either: a half-applied pass leaves a
    # tree no pass intended to produce.
    assert not (tmp_path / "app" / "models.py").exists()


def test_banner_is_added_once(tmp_path):
    write_all(tmp_path, [GeneratedFile("app/models.py", "x = 1\n")], "schema")
    first = (tmp_path / "app" / "models.py").read_text()
    assert first.startswith("# GENERATED by protogen (schema pass)")

    write_all(tmp_path, [GeneratedFile("app/models.py", first)], "schema")
    second = (tmp_path / "app" / "models.py").read_text()
    assert second.count("GENERATED by protogen") == 1
