"""The generated tree IS the test.

protogen has no way to assert that a prompt produced good code. What it can
assert is that the whole pipeline -- skeleton, five passes, write guard --
produces a tree whose own smoke suite passes. The offline baseline is what
makes that runnable in CI, with no API key and no Docker daemon.

The suite is run against SQLite rather than Postgres for the same reason: it
exercises the generated models, routes, templates, seed and form coercion,
which is where generation bugs live. Postgres-specific behaviour is not what
these files get wrong.
"""

from __future__ import annotations

import ast
import os
import subprocess
import sys
from pathlib import Path

import pytest

from protogen.llm import OfflineLLM
from protogen.passes import PassContext
from protogen.render import TOKEN_RE, render_skeleton
from protogen.build import generate

pytest.importorskip("fastapi")
pytest.importorskip("sqlalchemy")
jinja2 = pytest.importorskip("jinja2")

GENERATED = (
    "app/models.py",
    "app/routes.py",
    "app/seed.py",
    "tests/test_smoke.py",
)


@pytest.fixture()
def tree(spec, tmp_path) -> Path:
    render_skeleton(spec, tmp_path)
    spec.save(tmp_path)
    generate(spec, PassContext(project_dir=tmp_path), OfflineLLM(), log=lambda _: None)
    return tmp_path


def test_no_placeholder_survives_generation(tree):
    for path in tree.rglob("*"):
        if path.is_file() and path.suffix in {".py", ".html", ".yml", ".css", ".md", ".txt"}:
            assert not TOKEN_RE.search(path.read_text()), f"{path} kept a placeholder"


def test_every_python_file_parses(tree):
    for path in tree.rglob("*.py"):
        ast.parse(path.read_text(), str(path))


def test_every_template_parses(tree):
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(tree / "app" / "templates")))
    for path in (tree / "app" / "templates").glob("*.html"):
        env.parse(path.read_text(), filename=str(path))


def test_generated_files_carry_a_banner(tree):
    for rel in GENERATED:
        assert "GENERATED by protogen" in (tree / rel).read_text().split("\n", 2)[0]


def test_skeleton_files_were_not_touched(tree):
    for rel in ("Dockerfile", "compose.yml", "app/main.py", "app/db.py",
                "app/templates/base.html", "tests/conftest.py"):
        assert "GENERATED by protogen" not in (tree / rel).read_text()


def test_every_template_a_route_renders_exists(tree):
    """A template name invented in routes.py is a 500 at render time, and the
    only place it shows up before then is right here."""
    source = (tree / "app" / "routes.py").read_text()
    names = {
        node.args[1].value
        for node in ast.walk(ast.parse(source))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "TemplateResponse"
        and len(node.args) > 1
        and isinstance(node.args[1], ast.Constant)
    }
    assert names
    for name in names:
        assert (tree / "app" / "templates" / name).exists(), f"routes.py renders missing {name}"


def test_the_generated_app_passes_its_own_smoke_suite(tree):
    env = {
        **os.environ,
        "DATABASE_URL": f"sqlite:///{tree / 'dev.db'}",
        "APP_NAME": "Gear List",
        "APP_PURPOSE": "Track camping gear across trips.",
        "PYTHONDONTWRITEBYTECODE": "1",
    }
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "--no-header", "-p", "no:cacheprovider"],
        cwd=str(tree),
        env=env,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
