"""The drift allowlist can express the keys the drift checker asks about.

An escape hatch that cannot be used is worse than no escape hatch, because it
looks like one. This one could not: `check_workflow_drift.py` names a job
`<workflow>.yml:<job-id>`, and its allowlist reader split each line on the first
colon — so `ci.yml:integration: reason` parsed to the key `ci.yml` and matched
nothing the checker ever looked up. **No entry could exempt any job, ever.**

Nothing could see it. A fresh tree enrols no jobs and ships an empty allowlist,
so the check is green and stays green; the bug waits for the first person with a
deliberate divergence to record, who finds the check will not go quiet and
reasonably concludes the check is broken — and deletes it. That is the whole
failure mode this shell exists to prevent, arriving in the mechanism meant to
prevent it.

## Why this is a round-trip and not an example

The fix that matters is `key_for()`: one function owns the format, so the
checker and the reader read it from the same place. A test naming
`"ci.yml:integration"` as a literal would be a third copy of the format and
would keep passing after somebody changed it — the exact shape of mistake the
bug was. So the key here is *generated by the function under test* and written
through the real reader; nothing in this file spells the format.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit]

# Bootstrap only: put the package on sys.path so `scripts.paths` — which owns
# every path below — can be imported. See scripts/paths.py.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import check_workflow_drift as drift  # noqa: E402


def test_the_reader_parses_a_key_the_checker_would_ask_about(tmp_path, monkeypatch):
    key = drift.key_for("ci.yml", "integration")
    reason = "the smoke job stands the stack up differently: on purpose, see docs/DEVELOPMENT.md"
    allowlist = tmp_path / "workflow_drift_allowlist.yaml"
    allowlist.write_text(f"# a comment\n\n{key}: {reason}\n", encoding="utf-8")
    monkeypatch.setattr(drift, "ALLOWLIST", allowlist)

    parsed = drift._allowlist()

    # The key survives whole — this is the assertion the shipped reader failed.
    assert key in parsed, f"{key!r} did not survive the reader: got {sorted(parsed)}"
    # And the reason keeps its own colons, which is why the split is on ": ".
    assert parsed[key] == reason


def test_a_reason_is_not_optional(tmp_path, monkeypatch):
    """A bare key exempts something with no decision recorded behind it.

    The reader drops it rather than admitting it: an entry with no reason is
    indistinguishable from a line somebody half-typed, and the checker's whole
    claim is that an exemption is a decision record.
    """
    allowlist = tmp_path / "workflow_drift_allowlist.yaml"
    allowlist.write_text(f"{drift.key_for('ci.yml', 'integration')}\n", encoding="utf-8")
    monkeypatch.setattr(drift, "ALLOWLIST", allowlist)

    assert drift._allowlist() == {}
